# chrome_path = "/usr/bin/google-chrome"
# user_data_dir = "/home/pbs/Workspace/ChromeData"
chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
user_data_dir = "/Users/singhpra/Trading/ChromeDataDir"

chrome_args = []
launch_if_needed = true

rust_log="info,runner=debug"